add user authentication and profile page component
mstacey-codes/pastabilities pull request #1
Opened 2022-02-01 19:55 UTC by WoweeZowee94

Fleshed out pre-built authentication assets to create functioning authentication, user persistence, and a profile page for the current user.

2022-02-01 20:40 UTC, ohad-porat requested changes
Small and very well-scoped PR! Great work, one main thing to change is having some data to be displayed on the `UserProfile` page.

2022-02-01 20:40 UTC, ohad-porat commented on client/src/components/App.js
> +        <AuthenticatedRoute  exact path="/profile" component={UserProfile} user={currentUser} />
We want to have only one space after `AuthentucatedRoute`
```js
<AuthenticatedRoute exact path="/profile" component={UserProfile} user={currentUser} />
```

2022-02-01 20:40 UTC, ohad-porat commented on client/src/components/UserProfile.js
> +      <h2></h2>
Remove any unused elements

2022-02-01 20:40 UTC, ohad-porat commented on client/src/components/UserProfile.js
> +}
We expect complete features to have the data that we are expecting to see and not filler text. We should at the very least see some information about the user, even if in the future we plan on having something completely different on this page.

2022-02-02 15:44 UTC, WoweeZowee94 reviewed
Addressed changes suggested in first pass

2022-02-02 20:32 UTC, merged